### ISSUE TITLE
Add VPN Policy Routing?

### ISSUE THREAD

**Issue by ruralroots** [MarcoMihaiCondrache/NordVPN-OpenWrt#2]
Interesting. Might take a go at adding my current Wireshark/IPVanish VPN providers. 

Issue subject would be a nice option as it's critical to my current use situation.

**Comment by MarcoMihaiCondrache** [comment]
Hi, thanks for you issue reporting.

What do you mean by adding vpn policy routing?
Do you need a policy in particular or just the initial setup of vpr?

This could be an interesting feature to add.

**Comment by ruralroots** [comment]
@MarcoMihaiCondrache 
_ "What do you mean by adding vpn policy routing?
Do you need a policy in particular or just the initial setup of vpr?"_

No. I already have VPR setup with multiple policies working now. I can adapt your scripts for my current VPN providers, but I was just thinking after running through your code that I would also have to accommodate/adapt/sync my current VPR config as well.

**Comment by MarcoMihaiCondrache** [comment]
Can you past here the content of the file /etc/config/vpn-policy-routing just to see how the script should sync the configuration?

**Comment by ruralroots** [comment]
`config vpn-policy-routing 'config'
        option verbosity '2'
        option strict_enforcement '1'
        option src_ipset '0'
        list supported_interface 'vpn0'
        list ignored_interface 'vpnserver wgserver'
        option boot_timeout '30'
        option iptables_rule_option 'append'
        option iprule_enabled '0'
        option webui_sorting '1'
        list webui_supported_protocol 'tcp'
        list webui_supported_protocol 'udp'
        list webui_supported_protocol 'tcp udp'
        list webui_supported_protocol 'icmp'
        list webui_supported_protocol 'all'
        option ipv6_enabled '1'
        option webui_enable_column '1'
        option webui_chain_column '1'
        option webui_protocol_column '1'
        option dest_ipset '0'
        option resolver_ipset 'dnsmasq.ipset'
        option webui_show_ignore_target '0'
        option enabled '1' `

Pretty trivial. Just make sure interface name stays consistent:
`list supported_interface '**vpn0**`

**Comment by MarcoMihaiCondrache** [comment]
I've added vpr configuration as requested in the [commit](https://github.com/MarcoMihaiCondrache/NordVPN-OpenWrt/commit/ee66650b4cf9b404edfa2506713bf1d0c38c4706). Check if you need anything new. (I've changed some options check the README)
